### ISSUE TITLE
Command Dictionary for the mothership

### ISSUE THREAD

**Issue by CaptainSpaceCat** [kicksat/FlightSoftware#42]

**Comment by CaptainSpaceCat** [comment]
Command Dictionary:
- burn wire [1, 2, 3]
- downlink [n] data entries from sensor [1, 2, 3, 4, 5]
- write new register config file for sensor [1 - 5]
- downlink last [n] entries from config file
- enter arming mode

**Comment by ralent** [comment]
updated, pending final review, 7/19/18
